"""Runbook and execution plan generation for AIDOS."""

from __future__ import annotations

from typing import Any

import yaml

from aidos.schemas import CanonicalSoT, RunbookPlan, RunbookTask, ValidationReport


_INTENT_TO_PLAYBOOK = {
    "sync_netbox_intent": "claim_device_policy.yml",
    "configure_network": "network_connectivity_policy.yml",
    "provision_compute": "server_profile_template.yml",
    "post_deploy_health_check": "syslog_policy.yml",
}


def build_runbook_plan(
    sot: CanonicalSoT,
    report: ValidationReport,
    *,
    pyats_testbed_path: str | None = None,
) -> RunbookPlan:
    """Generate normalized runbook tasks from SoT + validation findings."""
    deployment = sot.intent.deployment_name
    post_check_executor = "pyats" if pyats_testbed_path else "cli"
    post_check_fallbacks = ["cli", "api", "ansible", "mcp", "playwright"]

    tasks = [
        RunbookTask(
            id="task-001",
            intent="sync_netbox_intent",
            target=deployment,
            preferred_executor="api",
            fallback_executors=["cli", "ansible", "mcp", "playwright"],
            preconditions=["sot_built"],
            approval_required=False,
        ),
        RunbookTask(
            id="task-002",
            intent="configure_network",
            target="switch-stack-a",
            preferred_executor="ansible",
            fallback_executors=["api", "cli", "mcp", "playwright"],
            preconditions=["netbox_synced", "validation_passed"],
            approval_required=True,
        ),
        RunbookTask(
            id="task-003",
            intent="provision_compute",
            target=deployment,
            preferred_executor="api",
            fallback_executors=["ansible", "cli", "mcp", "playwright"],
            preconditions=["netbox_synced", "validation_passed"],
            approval_required=True,
        ),
        RunbookTask(
            id="task-004",
            intent="post_deploy_health_check",
            target=deployment,
            preferred_executor=post_check_executor,
            fallback_executors=post_check_fallbacks,
            preconditions=["execution_complete"],
            approval_required=False,
        ),
    ]

    notes = [
        "Executor priority order: api > cli > ansible > mcp > playwright; post-check optionally promotes pyATS when configured.",
        f"Validation readiness at planning time: {report.readiness}",
    ]
    if pyats_testbed_path:
        notes.append(f"pyATS health-check enabled using testbed: {pyats_testbed_path}")
    else:
        notes.append("pyATS health-check not configured; post-deploy verification falls back to CLI.")
    if report.critical:
        notes.append("Critical findings exist: execution should remain approval-gated.")

    return RunbookPlan(deployment=deployment, tasks=tasks, notes=notes)


def build_ansible_playbook(plan: RunbookPlan) -> str:
    """Generate site.yml style master playbook importing child playbooks."""
    imports = []
    for task in plan.tasks:
        playbook_name = _INTENT_TO_PLAYBOOK.get(task.intent, f"{task.id}_{task.intent}.yml")
        imports.append({"import_playbook": f"playbooks/{playbook_name}"})
    return yaml.safe_dump(imports, sort_keys=False)


def build_ansible_bundle(plan: RunbookPlan) -> dict[str, str]:
    """Generate intersight-style ansible bundle files for operator usability."""
    files: dict[str, str] = {}

    files["README.md"] = "\n".join(
        [
            "# AIDOS Generated Ansible Bundle",
            "",
            "This bundle mirrors policy-oriented Intersight-style structure for clarity.",
            "",
            "## Quick Start",
            "",
            "1. Populate group_vars/all.yml from group_vars/all.yml.template",
            "2. Update inventory/hosts.yml as needed",
            "3. Run: ansible-playbook -i inventory/hosts.yml -e @group_vars/all.yml playbooks/site.yml",
            "",
            "## Generated from runbook",
            f"- Deployment: {plan.deployment}",
            f"- Tasks: {len(plan.tasks)}",
            "",
        ]
    )

    files["group_vars/all.yml.template"] = yaml.safe_dump(
        {
            "deployment_name": plan.deployment,
            "api_key_id": "SET_ME",
            "api_private_key": "SET_ME",
            "org_name": "SET_ME",
            "prefix": plan.deployment.upper().replace("-", "_"),
            "notes": "Generated by AIDOS planning module",
        },
        sort_keys=False,
    )
    files["group_vars/all.yml.example"] = files["group_vars/all.yml.template"]

    files["inventory/hosts.yml"] = yaml.safe_dump(
        {
            "all": {
                "hosts": {
                    "localhost": {
                        "ansible_connection": "local",
                    }
                }
            }
        },
        sort_keys=False,
    )

    site_imports = []
    for task in plan.tasks:
        playbook_name = _INTENT_TO_PLAYBOOK.get(task.intent, f"{task.id}_{task.intent}.yml")
        site_imports.append({"import_playbook": playbook_name})
        files[f"playbooks/{playbook_name}"] = yaml.safe_dump(
            [
                {
                    "name": f"AIDOS task {task.id} - {task.intent}",
                    "hosts": "localhost",
                    "gather_facts": False,
                    "tasks": [
                        {
                            "name": f"Execute {task.intent}",
                            "debug": {
                                "msg": (
                                    f"task_id={task.id} target={task.target} "
                                    f"preferred_executor={task.preferred_executor} "
                                    f"approval_required={task.approval_required}"
                                )
                            },
                        }
                    ],
                }
            ],
            sort_keys=False,
        )

    files["playbooks/site.yml"] = yaml.safe_dump(site_imports, sort_keys=False)
    return files


def build_agentic_task_graph(plan: RunbookPlan) -> dict[str, Any]:
    """Generate agentic task graph JSON for NemoClaw/Nemosys style runtime."""
    nodes = [
        {
            "id": task.id,
            "intent": task.intent,
            "target": task.target,
            "preferred_executor": task.preferred_executor,
            "fallback_executors": task.fallback_executors,
            "preconditions": task.preconditions,
            "approval_required": task.approval_required,
            "evidence_required": task.evidence_required,
        }
        for task in plan.tasks
    ]

    edges = []
    for idx in range(len(plan.tasks) - 1):
        edges.append({"from": plan.tasks[idx].id, "to": plan.tasks[idx + 1].id})

    return {
        "deployment": plan.deployment,
        "nodes": nodes,
        "edges": edges,
        "notes": plan.notes,
    }
